model:
  max_depth: 5

training:
  max_mse: 1e6  # Maximum acceptable Mean Squared Error

validation:
  min_r2_score: 0.0  # Temporarily set to 0 for test dataset
  max_mse: 30  # Maximum acceptable MSE for test dataset
