name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Cache Python Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest pytest-cov
          python -m pip install -r requirements.txt
          python -m pip install dvc[all] mlflow

      - name: Run Tests
        run: |
          PYTHONPATH=$PYTHONPATH:$(pwd) pytest tests/ --cov=src --cov-report=term-missing -v

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Setup DVC
        run: |
          rm -rf .dvc
          dvc init --no-scm
          dvc config core.no_scm true
          dvc config core.analytics false
          
      - name: Run DVC Pipeline
        run: |
          # Run DVC pipeline with force to ensure clean state
          dvc repro -v --force

      - name: Validate Model
        run: |
          python src/validate.py

      - name: Upload Model Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: models/best_model.pkl
          retention-days: 5

      - name: Build and Push Docker Image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build -t ${{ secrets.DOCKER_USERNAME }}/housing-api:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/housing-api:latest

      - name: Clean up
        if: always()
        run: |
          docker logout
